### PR TITLE
fix(database-memory): data not loading (#519)

### LINKED ISSUE #519: plugin-database-memory 无法正确加载数据库
由于懒得装数据库，我就试了一下 memory 数据库，但是每次机器人重启后数据就丢失了。

https://github.com/koishijs/koishi/blob/d1508f21a06d963941a99be6ce561887a889d565/plugins/database/memory/src/storage/node.ts#L27-L29

这里我通过调试发现 `extension` 的值是 `".json"`，而因为 `loader` 是 `"json"`，所以程序认为扩展名不匹配，跳过了加载。

### PR DESCRIPTION
**Pull request by DGCK81LNN**
fixed to make Storage.start() work (probably)
----
fixes #519
>looks like someone didn't realize that `path.extname()` includes the preceeding dot

### CODE REVIEW

File: plugins/database/memory/src/storage/node.ts [hunk 1]
```diff
@@ -26,11 +26,11 @@ export class Storage {
...
     await Promise.all(files.map(async (filename) => {
       const extension = extname(filename)
-      if (extension !== loader) return
-      const buffer = await fs.readFile(filename)
+      if (extension !== `.${loader}`) return
+      const buffer = await fs.readFile(resolve(root, filename))
       try {
         const data = await this.load(buffer, loader)
-        const name = filename.slice(0, -1 - extension.length)
+        const name = filename.slice(0, filename.length - extension.length)
```
Comment (Shigma) [inline plugins/database/memory/src/storage/node.ts:33]: maybe 

```ts
filename.slice(0, -extension.length)
```

is better?

**Review by Shigma — CHANGES_REQUESTED** [review]

File: plugins/database/memory/src/storage/node.ts (hunk 1 above)
Comment (DGCK81LNN) [reply plugins/database/memory/src/storage/node.ts:33]: I was considering that this will return an empty string if `extension` is empty but practically this never happens.

Comment (DGCK81LNN) [reply plugins/database/memory/src/storage/node.ts:33]: If someone modified the code to allow using data files without an extension then the use of `-extension.length` will break things.

Comment (Shigma) [reply plugins/database/memory/src/storage/node.ts:33]: That makes sense.

**Review by Shigma — APPROVED** [review]
