### PR TITLE
fix(mongo): db.totalSize can be undefined, fix #568

### LINKED ISSUE #568: Bug: 控制台界面 显示数据库未安装
### Describe the bug

安装的数据库是MongoDB 成功连接数据库后,控制台界面 显示数据库未安装
image

### Steps to reproduce

yarn 创造的项目 使用的数据库是MongoDB

### Expected behavior

显示正常

### Screenshots

_No response_

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version: 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaikoTan**
https://www.mongodb.com/docs/manual/reference/command/dbStats/#mongodb-data-dbStats.totalSize
While MongoDB's document above says that the `stats.totalSize` is the sum of
 `stats.dataSize` and `stats.storageSize`, it's actually `undefined` in some cases.
So we have to calculate it manually.

### CODE REVIEW

File: plugins/database/mongo/src/index.ts [hunk 1]
```diff
@@ -119,10 +119,15 @@ class MongoDatabase extends Database {
 
   async stats() {
     // https://docs.mongodb.com/manual/reference/command/dbStats/#std-label-dbstats-output
-    const [{ totalSize }, tables] = await Promise.all([
+    const [stats, tables] = await Promise.all([
       this.db.stats(),
       this._collStats(),
     ])
+    // https://www.mongodb.com/docs/manual/reference/command/dbStats/#mongodb-data-dbStats.totalSize
```
Comment (MaikoTan) [inline plugins/database/mongo/src/index.ts:126]:
```suggestion

```

**Review by Shigma — APPROVED** [review]
